import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes';


import { Edu_AU_VIC_WA_NT_Hand } from "next/font/google";

const eduVIC = Edu_AU_VIC_WA_NT_Hand({
  subsets: ["latin"],
  variable: "--font-edu-vic", // this defines a CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          fontFamily: 'Roboto, sans-serif',
        },
        elements: {
          '*': 'font-roboto',
          profileNavbar: 'font-roboto',
          profilePage: 'font-roboto',
        },
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${eduVIC.variable} antialiased md:mx-20`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="container">
            {/* <div className="mx-10"> */}
              <Navbar />
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
